notifications:
  email: false

language: php

php:
  - 7.3
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - composer install
  - chmod -R +x ./bin

script:
  - ./bin/phpspec run
