notifications:
  email: false

language: php

php:
  - 7.3
  - 7.4snapshot
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: hhvm
    - php: nightly

sudo: false

before_script:
  - if [[ $TRAVIS_PHP_VERSION = nightly ]]; then export COMPOSER_FLAGS=" --ignore-platform-reqs"; fi
  - composer install --prefer-source $COMPOSER_FLAGS
  - chmod -R +x ./bin

script:
  - ./bin/phpspec run
