name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: phpactions/composer@master
    - name: phpspec
      uses: phpactions/phpspec@master
      with:
        config: phpspec.yml


